on: [push, pull_request, workflow_dispatch]

jobs:
  convert-to-markdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: install pipenv
        run: |
          python3 -m install --upgrade pipenv wheel
      
      - name: install dependencies
        run: |
          pipenv install 
      
      - name: Extract Branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Convert docx to markdown
        run: python3 ./.github/workflows/convert_to_md.py
    

