on: [push, pull_request, workflow_dispatch]

jobs:
  convert-to-markdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: install pipenv
        run: |
          python -m pip install pipenv
      
      - name: install dependencies
        run: |
          pipenv install 
      
      - name: Extract Branch name
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo ${GITHUB_REF#refs/heads/}
        id: extract_branch

      - name: Convert docx to markdown
        run: |
          pipenv shell
          python ./.github/workflows/convert_to_md.py
    

