on: [push, pull_request, workflow_dispatch]

jobs:
  convert-to-markdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: install pipenv
        run: |
          python -m pip install pipenv
      
      - name: install dependencies
        run: |
          pipenv lock -r > requirements.txt
          pip install -r requirements.txt 
      
      - name: Extract Branch name
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo ${GITHUB_REF#refs/heads/}
        id: extract_branch

      - name: Convert docx to markdown
        run: | 
          python ./.github/workflows/convert_to_md.py

      - name: Check if Diff
        id: git_diff
        run: |
          git diff
          echo "::set-output name=git_diff::${?}"
        outputs:
          git_diff: ${{steps.git_diff.outputs.git_diff}}

      - name: Commit markdown to branch
        if: ${{ convert_to_md.outputs.git_diff != 0 }}
        run: |
          git add .
          git config --local user.email "commit from ${GITHUB_REF#refs/heads/}"
          git config --local user.name "Github Actions"
          git commit -m "convert to md"

          git push origin ${GITHUB_REF#refs/heads/}
    

